export const AssetsDB = {
  "audio": {
    "car": "car",
    "chest_hit": "chest_hit",
    "click": "click",
    "jump": "jump",
    "music": "music",
    "push": "push",
    "wheel": "wheel",
    "win": "win"
  },
  "font": {
    "Roboto": "Roboto"
  },
  "data": {
    "cars": "cars",
    "chest": "chest",
    "chicken": "chicken",
    "packshot_block": "packshot_block",
    "vfx_coins": "vfx_coins",
    "vfx_confetti": "vfx_confetti"
  },
  "texture": {
    "cars_tex": "cars_tex",
    "chest_tex": "chest_tex",
    "chicken_bage": "chicken_bage",
    "chicken_tex": "chicken_tex",
    "barrier": "barrier",
    "hatch_active": "hatch_active",
    "hatch_complete": "hatch_complete",
    "hatch_deactive": "hatch_deactive",
    "level_divider": "level_divider",
    "level_finish": "level_finish",
    "level_start": "level_start",
    "Bank": "Bank",
    "icon_amazon": "icon_amazon",
    "icon_game": "icon_game",
    "icon_netflix": "icon_netflix",
    "icon_uber": "icon_uber",
    "controls_mid": "controls_mid",
    "controls_top": "controls_top",
    "cursor2": "cursor2",
    "hand": "hand",
    "loading_background": "loading_background",
    "loading_border": "loading_border",
    "loading_logo": "loading_logo",
    "logo": "logo",
    "players_online": "players_online",
    "players_panel": "players_panel",
    "player_01": "player_01",
    "player_02": "player_02",
    "player_03": "player_03",
    "player_04": "player_04",
    "packshot_app": "packshot_app",
    "packshot_background_hor": "packshot_background_hor",
    "packshot_background_ver": "packshot_background_ver",
    "packshot_block_tex": "packshot_block_tex",
    "packshot_btn": "packshot_btn",
    "packshot_chicken": "packshot_chicken",
    "packshot_google": "packshot_google",
    "bonus_panel": "bonus_panel",
    "arrow": "arrow",
    "rool": "rool",
    "spine": "spine",
    "vfx_coins_tex": "vfx_coins_tex",
    "vfx_confetti_tex": "vfx_confetti_tex"
  }
};