export const AssetsDB = {
  "audio": {
    "car": "car",
    "click": "click",
    "coin": "coin",
    "jump": "jump",
    "music": "music",
    "wheel": "wheel"
  },
  "font": {
    "Cera": "Cera"
  },
  "data": {
    "cars": "cars",
    "chest": "chest",
    "chicken": "chicken",
    "packshot_block": "packshot_block",
    "vfx_coins": "vfx_coins",
    "vfx_confetti": "vfx_confetti"
  },
  "texture": {
    "cars_tex": "cars_tex",
    "chest_tex": "chest_tex",
    "chicken_bage": "chicken_bage",
    "chicken_tex": "chicken_tex",
    "barrier": "barrier",
    "hatch_active": "hatch_active",
    "hatch_complete": "hatch_complete",
    "hatch_deactive": "hatch_deactive",
    "level_divider": "level_divider",
    "level_finish": "level_finish",
    "level_start": "level_start",
    "rool": "rool",
    "spine": "spine",
    "434x0w": "434x0w",
    "Bank": "Bank",
    "icon_amazon": "icon_amazon",
    "icon_game": "icon_game",
    "icon_netflix": "icon_netflix",
    "icon_uber": "icon_uber",
    "controls_top": "controls_top",
    "cursor": "cursor",
    "loading_background": "loading_background",
    "loading_border": "loading_border",
    "loading_logo": "loading_logo",
    "logo": "logo",
    "Player 04": "Player 04",
    "players_online": "players_online",
    "players_panel": "players_panel",
    "player_01": "player_01",
    "player_02": "player_02",
    "player_03": "player_03",
    "packshot_app": "packshot_app",
    "packshot_background": "packshot_background",
    "packshot_block_tex": "packshot_block_tex",
    "packshot_btn": "packshot_btn",
    "packshot_chicken": "packshot_chicken",
    "packshot_google": "packshot_google",
    "vfx_coins_tex": "vfx_coins_tex",
    "vfx_confetti_tex": "vfx_confetti_tex"
  }
};